---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Purge vendored CNAME
        run: rm ./playground-8b71eafaca7c1d43c0149c7860847ed40de550a3/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/trunk'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playground-8b71eafaca7c1d43c0149c7860847ed40de550a3
          publish_branch: gh-pages
          cname: rubyconf2019.artichoke.run
          user_name: artichoke-ci
          user_email: ci@artichokeruby.org

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint and check formatting with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          sudo -H python3 -m pip install --upgrade pip setuptools wheel
          sudo -H python3 -m pip install --upgrade yamllint
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict .
          echo "OK"
